name: ESP32-CI-CD
on:
  push:
    branches:
      - main

jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Repo checkout
#        uses: actions/checkout@v3
#        with:
#          submodules: 'recursive'
#
#      - name: Espressif IoT Development Framework (ESP-IDF)
#        uses: espressif/esp-idf-ci-action@v1.1.0
#        with:
#          esp_idf_version: v4.4
#          target: esp32

  test:
    runs-on: ubuntu-latest
#    needs: [build]
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: Build unit tests
        uses: espressif/esp-idf-ci-action@v1.1.0
        with:
          esp_idf_version: v4.4
          target: esp32
          path: test

      - name: Flash in the ESP32
        uses: espressif/esp-idf-ci-action@v1.1.0
        with:
          esp_idf_version: v4.4
          target: esp32
          path: test
          command: idf.py -p /dev/ttyUSB0 flash


#      - name: Store Artifacts
#        uses: actions/upload-artifact@v3
#        with: 
#          name: unit-tests.xml
#          path: |
#            build/test.xml

#      - name: Show result tests
#        uses: EnricoMi/publish-unit-test-result-action@v2
#        if: always()
#        with:
#            files: test.xml
