name: ESP32-CI-CD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Espressif IoT Development Framework (ESP-IDF)
        uses: espressif/esp-idf-ci-action@v1.1.0
        with:
          esp_idf_version: v4.4
          target: esp32

      - name: Store Artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: release
          path: |
            build/ESP32-CI-CD.bin

      - name: partitions.csv
        run: |
          cd build
          wget https://github.com/espressif/arduino-esp32/blob/21b88659b9ded3fcc1082f23f498bc2a04cd4f1b/tools/partitions/default.csv

      - name: ESP32 QEmu Runner
        uses: tobozo/esp32-qemu-sim@1.0.0
        with:
         flash-size: 4
         build-folder: build
         qemu-timeout: "60"

#  test:
#    runs-on: ubuntu-latest
#    needs: [build]
#    steps:
#      - name: Repo checkout
#        uses: actions/checkout@v3

#      - name: Build unit tests
#        uses: espressif/esp-idf-ci-action@v1.1.0
#        with:
#          esp_idf_version: v4.4
#          target: esp32
#          path: test

#      - name: Store Artifacts
#        uses: actions/upload-artifact@v3
#        with: 
#          name: unit-test
#          path: |
#            test/build/unitExample.bin

#  runner:
#    runs-on: ubuntu-latest
#    needs: [build]
#    steps:
#      - name: Repo checkout
#        uses: actions/checkout@v3

#      - name: ESP32 QEmu Runner
#        uses: tobozo/esp32-qemu-sim@1.0.0
#        with:
#         flash-size: 4
#         qemu-timeout: "60"

#      - name: ESP32 Unit Test QEmu Runner
#        uses: tobozo/esp32-qemu-sim@1.0.0
#        with:
#          flash-size: 4
#          build-folder: test/build
#          qemu-timeout: "60"        
  
