name: ESP32-CI-CD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Espressif IoT Development Framework (ESP-IDF)
        uses: espressif/esp-idf-ci-action@v1.1.0
        with:
          esp_idf_version: v4.4
          target: esp32

      - name: Store Artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: release
          path: |
            build/ESP32-CI-CD.bin


  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: Build unit tests
        uses: espressif/esp-idf-ci-action@v1.1.0
        with:
          esp_idf_version: v4.4
          target: esp32
          path: test

      - name: Store Artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: unit-test
          path: |
            ESP32-CI-CD/test/build/unitExample.bin
